[package]
name = "fastann"
version = "0.1.0"
authors = ["salamer <salamer_gaga@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.1.32"
rand = "0.7.3"